sudo: true

language: cpp

compiler:
  - g++

services:
  - docker

before_install:
  - docker pull ubuntu:17.10
  - docker run -it ubuntu bash

install:
  - apt-get update
  - apt-get install graphicsmagick
  - apt-get install qt5-default

script: "bash -c ./build.sh"
