sudo: required

language: cpp

compiler:
- g++

services:
- docker

before_install:
- docker pull ubuntu:16.04
- docker run -t -i ubuntu /bin/bash

install:
- sudo apt-get install graphicsmagick
- sudo apt-get install qt5-default

script: "bash -c ./build.sh"