sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull ubuntu:latest

script:
  - docker run -v "$(pwd):/var/photoflare" ubuntu:latest /bin/sh -c "cd /var/photoflare/ && ./build.sh"
