apps: 
  photoflare:
    command: desktop-launch usr/bin/photoflare
name: photoflare
summary: PhotoFlare
confinement: devmode
version: 1.5.3
description: Simple but powerful Cross Platform image editor.
parts:
  photoflare:
    after: [desktop-qt5]
    source: ../
    source-type: git
    source-tag: 'v1.5.3'
    source-depth: 1
    plugin: qmake
    qt-version: qt5
    build-packages:
      - g++
      - qt5-default
      - libgraphicsmagick++-dev
    stage-packages:
      - libc6
      - libgraphicsmagick++-q16-12
      - libqt5gui5
      - libqt5core5a
      - libqt5widgets5
